---
-
  hosts: experiments
  user: ubuntu
  tasks:
  - shell: uname -a
    ignore_errors: yes
    register: uname_result
  - name: Install apt packages
    become: true
    apt:
      state: present
      update_cache: yes
      name:
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - vim
        - curl
        - bpftrace
        - trace-cmd
        - perf
        - linux-headers-{{ uname_result.stdout }}
        - linux-tools-{{ uname_result.stdout }}
        - bpfcc-tools
